In [49]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
#The version string is stored under __version__ attribute.
print(np.__version__)
#type(): This built-in Python function tells us the type of the object passed to it
print(type(arr))
#An array that has 1-D arrays as its elements is called a 2-D array.
a=np.array([[1,2],[3,4]])
print(a)
#ndim attribute that returns an integer that tells us how many dimensions the array have.
print('number of dimensions :',a.ndim)
print("second element from the arrays is:",a[1])
#Slicing arrays
#We pass slice instead of index like this: [start:end]
#We can also define the step, like this: [start:end:step]
print("slicing the array:",arr[1:4])
print(arr[:4])
#dtype that returns the data type of the array
print(arr.dtype)
b = np.array([5.1, 678.1, 3444.1])
#astype() function creates a copy of the array, and allows you to specify the data type as a parameter.
newarr = b.astype('S')
print(newarr)
print(newarr.dtype)

x = b.copy()
g=x.view()
g[2]=455
b[0] = 42
#base  attribute refers to the original object
x = b.copy()
g = b.view()
print(x.base)
print(g.base)
print(b)
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
#shape that returns a tuple with each index having the number of corresponding elements.
print('shape of array :', arr.shape)
#iterating the arrays

for x in a:
    print("iterating 2d array:-",a)
#joining two arrays using concatinating()
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.concatenate((arr1, arr2))
print("joining two arrays:-",arr3)
#array_split() for splitting arrays, we pass it the array we want to split and the number of splits.
newarr = np.array_split(arr, 2)
print("spliting the array:-",newarr)
#You can search an array for a certain value, and return the indexes that get a match.To search an array, use the where() method.
v= np.where(arr%2 == 1)
print(v)
#Sorting means putting elements in an ordered sequence.
sus = np.array(['banana', 'cherry', 'apple'])
print(np.sort(sus))




[1 2 3 4 5]
1.21.5
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]
number of dimensions : 2
second element from the arrays is: [3 4]
slicing the array: [2 3 4]
[1 2 3 4]
int32
[b'5.1' b'678.1' b'3444.1']
|S32
None
[  42.   678.1 3444.1]
[  42.   678.1 3444.1]
[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)
iterating 2d array:- [[1 2]
 [3 4]]
iterating 2d array:- [[1 2]
 [3 4]]
joining two arrays:- [1 2 3 4 5 6]
spliting the array:- [array([[[[[1, 2, 3, 4]]]]]), array([], shape=(0, 1, 1, 1, 4), dtype=int32)]
(array([0, 0], dtype=int64), array([0, 0], dtype=int64), array([0, 0], dtype=int64), array([0, 0], dtype=int64), array([0, 2], dtype=int64))
['apple' 'banana' 'cherry']


In [50]:
#Getting some elements out of an existing array and creating a new array out of them is called filtering.
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7])
# Create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, False, True, False, True, False]
[2 4 6]


In [54]:
#Numpy random
from numpy import random
x = random.randint(100)
#rand() method returns a random float between 0 and 1.
y = random.rand()
#randint() method takes a size parameter where you can specify the shape of an array.
z=random.randint(100, size=(5))
print(x)
print(y)
print(z)

35
0.49873831742788566
[52 77 88  7 90]


In [59]:
#choice() method allows us to specify the probability for each value.
from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3,5))
print(x)

[[7 7 7 5 5]
 [5 7 7 5 7]
 [7 5 5 5 7]]


In [63]:
#Shuffle means changing arrangement of elements in-place. i.e. in the array itself.
#shuffle() method makes changes to the original array.
#permutation() method returns a re-arranged array (and leaves the original array un-changed).
from numpy import random
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr1=np.array([11,14,18,12,2021])
random.shuffle(arr)
random.permutation(arr1)
print(arr)
print(random.permutation(arr1))


[3 1 5 2 4]
[  18   14   11 2021   12]


In [64]:
#loc - (Mean) where the peak of the bell exists.
#scale - (Standard Deviation) how flat the graph distribution should be.
#size - The shape of the returned array.
from numpy import random
x = random.normal(loc=1, scale=2, size=(2, 3))
print(x)

[[-2.32332363  1.03632767 -1.49273445]
 [ 2.92605112 -0.96720843  1.15527658]]
